### ISSUE TITLE
在使用pytorch1.3版本，运行demo-recognize.py报错

### ISSUE THREAD

**Issue by anshenLW** [libai3/masr#100]
错误如下：
(gpu) [root@ai_174 examples]# python demo-recognize.py 
Traceback (most recent call last):
  File "demo-recognize.py", line 6, in <module>
    text = model.predict("/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/test.wav")
  File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 64, in predict
    out = self.cnn(spec)
  File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big

**Comment by zhangxj2020-cpu** [comment]
回滚到torch==1.0.1 就不报错了

**Comment by leisurehippo** [comment]
> 回滚到torch==1.0.1 就不报错了

我是torch==1.0.1但依旧是报这个错误，请问下您的cuda版本以及其他环境

**Comment by friendmine** [comment]
表示，用另外一个语音文件，这个demo是个10秒的。
please use your own wav file, the demo wav is a 10s.

**Comment by zhangxj2020-cpu** [comment]
> > 回滚到torch==1.0.1 就不报错了
> 
> 我是torch==1.0.1但依旧是报这个错误，请问下您的cuda版本以及其他环境

我的cuda版本是9.0，你要找你的cuda版本对应的torth版本，去官网看下，一起安装

**Comment by zhangxj2020-cpu** [comment]
> 错误如下：
> (gpu) [root@ai_174 examples]# python demo-recognize.py
> Traceback (most recent call last):
> File "demo-recognize.py", line 6, in 
> text = model.predict("/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/test.wav")
> File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 64, in predict
> out = self.cnn(spec)
> File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
> input = module(input)
> File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 18, in forward
> x = self.conv(x)
> File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: code is too big

朋友你的cuda版本是多少，这个问题解决了吗

**Comment by bigcash** [comment]
有人知道这个是什么原因嘛，回滚到torch==1.0.1，还是报错的。
我的cuda是10.2，pytorch1.0.1,之前是torch1.3.1时也是报这个错误的

**Comment by mukangt** [comment]
> > 错误如下：
> > (gpu) [root@ai_174 examples]# python demo-recognize.py
> > Traceback (most recent call last):
> > File "demo-recognize.py", line 6, in
> > text = model.predict("/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/test.wav")
> > File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 64, in predict
> > out = self.cnn(spec)
> > File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
> > input = module(input)
> > File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/home/nlp_group/lw/FFCTG/CTGSpeech/DEEPASR/examples/../models/conv.py", line 18, in forward
> > x = self.conv(x)
> > File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/usr/local/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
> > self.padding, self.dilation, self.groups)
> > RuntimeError: code is too big
> 
> 朋友你的cuda版本是多少，这个问题解决了吗

不是cuda版本的问题，应该是cpu型号的问题[https://github.com/NVIDIA/tacotron2/issues/125](url)

**Comment by Strong-Gavin** [comment]
解决了 我也遇到这个问题了 在本机虚拟机可以运行 但是放服务器 就不行 是不是这个必须依赖显卡
