### ISSUE TITLE
请求各位大佬指点labels.json文件格式和内容，有脚本贴上最好在线等，有重酬。

### ISSUE THREAD

**Issue by zhangxj2020-cpu** [libai3/masr#101]
[
   '_', 
   '移',
   '动',
   '叮',
   '的',
   '偏',
   '旁',
   '部',
   '首',
   '的',
   '位',
   '置',
   '改',
   '变',
   '叮',
   '的',
   '偏',
   '旁'
]
我用这个格式训练时报错了。

Traceback (most recent call last):
  File "train_zxj.py", line 115, in <module>
    vocabulary = json.load(f)
  File "/data/anacond3/anacond3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/data/anacond3/anacond3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/data/anacond3/anacond3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/anacond3/anacond3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 4 (char 5)
提示json格式不对

**Comment by zhangxj2020-cpu** [comment]
这个问题已经解决了，json数组结构放在txt里应该是用双引号。
["_ ",
"移",
"动",
"叮",
"的",
"偏",
"旁",
"部",
"首",
"的",
"位",
"置",
"改",
"变",
"叮"]

**Comment by ty839150290** [comment]
json文件写好之后，需要改其他代码吗？读取json文件还是报错
Traceback (most recent call last):
  File "C:/Users/yMichaelqh/PycharmProjects/masr/train.py", line 114, in <module>
    vocabulary = json.load(f)
  File "C:\Users\yMichaelqh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 9: illegal multibyte sequence

**Comment by ty839150290** [comment]
[
"_",
"火"，
"警",
"急",
"救",
"察",
]

**Comment by zhangxj2020-cpu** [comment]
修改一下txt数据编码，改成utf-8

**Comment by ty839150290** [comment]
谢谢大佬啦，解决了
