### ISSUE TITLE
关于如何训练模型及使用

### ISSUE THREAD

**Issue by Damahou9** [libai3/masr#103]
Traceback (most recent call last):
  File "/home/chen/masr/examples/demo-recognize.py", line 4, in <module>
    model = GatedConv.load("../pretrained/model_hello.pth")
  File "/home/chen/masr/examples/../models/base.py", line 13, in load
    state_dict = package["state_dict"]
TypeError: 'GatedConv' object is not subscriptable
我安照作者的步骤，进行了简单的训练，也不知道是不是训练的原因。使用时出现了这个错误，有人能帮忙解答吗，谢谢

**Comment by zhangxj2020-cpu** [comment]
我训练一半的时候停了也遇到同样的问题，目前不知道怎么解决，请大神指点了

**Comment by zhangxj2020-cpu** [comment]
> Traceback (most recent call last):
> File "/home/chen/masr/examples/demo-recognize.py", line 4, in 
> model = GatedConv.load("../pretrained/model_hello.pth")
> File "/home/chen/masr/examples/../models/base.py", line 13, in load
> state_dict = package["state_dict"]
> TypeError: 'GatedConv' object is not subscriptable
> 我安照作者的步骤，进行了简单的训练，也不知道是不是训练的原因。使用时出现了这个错误，有人能帮忙解答吗，谢谢

兄弟问题解决了吗，我训练一半的时候停了训练程序，然后拿一个模型来跑数据遇到同样的问题，目前不知道怎么解决，请指点。

**Comment by zhangxj2020-cpu** [comment]
> Traceback (most recent call last):
> File "/home/chen/masr/examples/demo-recognize.py", line 4, in 
> model = GatedConv.load("../pretrained/model_hello.pth")
> File "/home/chen/masr/examples/../models/base.py", line 13, in load
> state_dict = package["state_dict"]
> TypeError: 'GatedConv' object is not subscriptable
> 我安照作者的步骤，进行了简单的训练，也不知道是不是训练的原因。使用时出现了这个错误，有人能帮忙解答吗，谢谢

https://github.com/libai3/masr/issues/63  在这里，我试了可以解决这个问题

**Comment by Damahou9** [comment]
> > Traceback (most recent call last):
> > File "/home/chen/masr/examples/demo-recognize.py", line 4, in
> > model = GatedConv.load("../pretrained/model_hello.pth")
> > File "/home/chen/masr/examples/../models/base.py", line 13, in load
> > state_dict = package["state_dict"]
> > TypeError: 'GatedConv' object is not subscriptable
> > 我安照作者的步骤，进行了简单的训练，也不知道是不是训练的原因。使用时出现了这个错误，有人能帮忙解答吗，谢谢
> 
> #63 在这里，我试了可以解决这个问题

OK，感谢老哥！
