### ISSUE TITLE
跑docker报错

### ISSUE THREAD

**Issue by zg9uagfv** [libai3/masr#110]
os:ubuntu18.04
docker:Docker version 18.09.7, build 2d0083d

`root@Geek:/home/dh/Projects/masr# docker run -v $(pwd):/workspace/masr -p 5000:5000 libai3/masr-env:latest
Loading model...
Traceback (most recent call last):
  File "examples/demo-server.py", line 9, in <module>
    import beamdecode
  File "/workspace/masr/examples/../beamdecode.py", line 17, in <module>
    model = GatedConv.load("pretrained/gated-conv.pth")
  File "/workspace/masr/examples/../models/base.py", line 12, in load
    package = torch.load(path)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/gated-conv.pth'
`

**Comment by XingyuTian-Doggy** [comment]
No such file or directory: 'pretrained/gated-conv.pth'
检查一下路径吧~↑

**Comment by ming9080** [comment]
Can someone upload all the pre-trained networks to Google drive? I do not have access to Baidu.
