### ISSUE TITLE
RuntimeError: Working outside of request context

### ISSUE THREAD

**Issue by septnn** [libai3/masr#119]
平台：windows 10
环境：docker toolbox
镜像：libai3/masr-env:latest
命令：docker run
报错：docker logs 如下：
Loading model...
Model loaded
Traceback (most recent call last):
  File "examples/demo-server.py", line 13, in <module>
    f = request.files["file"]
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/opt/conda/lib/python3.6/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

**Comment by septnn** [comment]
内存不足导致Killed
