### ISSUE TITLE
录音达到5秒钟就报错Audio buffer is not finite everywhere

### ISSUE THREAD

**Issue by ForgetThatNight** [libai3/masr#132]
`/home/ml/masr/examples/../feature.py:20: RuntimeWarning: invalid value encountered in true_divide
  wav = (wav - wav.mean()) / wav.std()
Traceback (most recent call last):
  File "examples/predict.py", line 21, in <module>
    print(beamdecode.predict(file))
  File "/home/ml/masr/examples/../beamdecode.py", line 39, in predict
    spec = feature.spectrogram(wav)
  File "/home/ml/masr/examples/../feature.py", line 26, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere`
哪位大佬能帮忙解决啊？

**Comment by ForgetThatNight** [comment]
/home/ml/masr/examples/../feature.py:20: RuntimeWarning: invalid value encountered in true_divide
  wav = (wav - wav.mean()) / wav.std()
Traceback (most recent call last):
  File "examples/predict.py", line 21, in <module>
    print(beamdecode.predict(file))
  File "/home/ml/masr/examples/../beamdecode.py", line 39, in predict
    spec = feature.spectrogram(wav)
  File "/home/ml/masr/examples/../feature.py", line 26, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
格式有问题，重新加了一个
