### ISSUE TITLE
部分音频： code is too big

### ISSUE THREAD

**Issue by Honghe** [libai3/masr#16]
Environment:
- Ubuntu 18.04
- Conda 4.6.7
- Pytorch-GPU 1.1

测试音频文件于文末附件中。
```
python examples/demo-recognize.py 
Traceback (most recent call last):
  File "examples/demo-recognize.py", line 6, in <module>
    text = model.predict("test.wav")
  File "/home/ubuntu/honghe/masr/examples/../models/conv.py", line 62, in predict
    out = self.cnn(spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/honghe/masr/examples/../models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 187, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big
```

直接使用`test.wav`预测，`examples/demo-recognize.py`内容如下：
```
import _init_path
from models.conv import GatedConv

model = GatedConv.load("pretrained/gated-conv.pth")

text = model.predict("test.wav")

print("")
print("识别结果:")
print(text)
```

使用Pytorch-cpu版好像没问题。

[D4_752.zip](https://github.com/libai3/masr/files/3384864/D4_752.zip)

**Comment by lukhy** [comment]
我无法复现这个问题。

**Comment by baudzhou** [comment]
我也遇到了同样的问题
`Traceback (most recent call last):
  File "examples/demo-recognize.py", line 6, in <module>
    text = model.predict("test.wav")
  File "/home/user/Documents/dl/masr/examples/../models/conv.py", line 62, in predict
    out = self.cnn(spec)
  File "/home/user/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/user/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Documents/dl/masr/examples/../models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/home/user/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big
`

**Comment by maxxiayixiayi** [comment]
root@c6e9a9127e47:/public1/home/xiayi/SpeechRecognition/masr# python3.5 examples/demo-recognize.py
Traceback (most recent call last):
  File "examples/demo-recognize.py", line 6, in <module>
    text = model.predict("test.wav")
  File "/public1/home/xiayi/SpeechRecognition/masr/examples/../models/conv.py", line 62, in predict
    out = self.cnn(spec)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/public1/home/xiayi/SpeechRecognition/masr/examples/../models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 187, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big

**Comment by YasinZhao** [comment]
我也遇到了同样的问题。。。

**Comment by Augustusmyc** [comment]
我也遇到了一样的报错信息，怀疑跟cuda版本有关系。不知道楼上有谁解决了这个问题么？ @YasinZhao @baudzhou @Honghe @maxxiayixiayi

**Comment by zhouhao-learning** [comment]
这根本就不是语言模型啊,

**Comment by Honghe** [comment]
@libai3 不是语言模型问题，应该是对部分音频有问题，已上传测试音频，见一楼更新。

**Comment by genghuan2005** [comment]
> 我也遇到了一样的报错信息（用的centos + CUDA10 + python 3.6, pytorch官网上用conda安装的最新版本），怀疑跟cuda版本或者pytorch版本有关系。不知道楼上有谁解决了这个问题么？ @YasinZhao @baudzhou @Honghe @maxxiayixiayi
我也遇到同样的问题，请问解决了吗?

**Comment by EnzoLiang** [comment]
我用的docker镜像运行的，也遇到了这个问题，不知道你们解决了没有

**Comment by genghuan2005** [comment]
> 我用的docker镜像运行的，也遇到了这个问题，不知道你们解决了没有

请问，你的问题解决了吗？

**Comment by feifaxiaoming** [comment]
ubuntu16.04运行就报错

**Comment by feifaxiaoming** [comment]
报的也是这个问题，但是我的是cpu的，如果是gpu就不会有这个问题了

**Comment by Strong-Gavin** [comment]
我也遇到这个问题 请问解决了吗

**Comment by icegomic** [comment]
我也遇到这个问题  如何解决呢

**Comment by Strong-Gavin** [comment]
我是在我自己笔记本上可以用 但是放到私有云平台就不行了

**Comment by icegomic** [comment]
https://github.com/pytorch/pytorch/issues/24174    我找到了一个解答 目前还在尝试 如果有成功的 麻烦说一下

**Comment by Strong-Gavin** [comment]
> [pytorch/pytorch#24174](https://github.com/pytorch/pytorch/issues/24174) 我找到了一个解答 目前还在尝试 如果有成功的 麻烦说一下

如果你成功 麻烦贴下步骤 感谢

**Comment by icegomic** [comment]
我解决了   去pytorch官网下载开发版，不要用稳定版，开发版里面修复了这个问题。conda install pytorch torchvision cudatoolkit=10.1 -c pytorch-nightly

**Comment by icegomic** [comment]
可以了   去pytorch官网下载那个开发版


| |
凌冰
|
|
fate321@yeah.net
|
签名由网易邮箱大师定制


在2020年04月3日 17:15，Gavin<notifications@github.com> 写道：

pytorch/pytorch#24174 我找到了一个解答 目前还在尝试 如果有成功的 麻烦说一下

如果你成功 麻烦贴下步骤 感谢

**Comment by Strong-Gavin** [comment]
> 可以了 去pytorch官网下载那个开发版 | | 凌冰 | | fate321@yeah.net | 签名由网易邮箱大师定制 在2020年04月3日 17:15，Gavin<notifications@github.com> 写道： [pytorch/pytorch#24174](https://github.com/pytorch/pytorch/issues/24174) 我找到了一个解答 目前还在尝试 如果有成功的 麻烦说一下 如果你成功 麻烦贴下步骤 感谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你的是什么环境 不是docker吗 还有没有用作者那种方式安装torch吗 新版本pytorch和numpy和项目也兼容是吗 麻烦贴一下你的环境版本吧

**Comment by Strong-Gavin** [comment]
> 我解决了 去pytorch官网下载开发版，不要用稳定版，开发版里面修复了这个问题。conda install pytorch torchvision cudatoolkit=10.1 -c pytorch-nightly

下载开发版了 但是ctcdecode好像不支持了 报错了 ctcdecode只能用1.0版本啊

**Comment by Strong-Gavin** [comment]
> 我解决了 去pytorch官网下载开发版，不要用稳定版，开发版里面修复了这个问题。conda install pytorch torchvision cudatoolkit=10.1 -c pytorch-nightly

你用语言模型了吗 ctcdecode在新版本torch 怎么用的
