### ISSUE TITLE
运行示例demo-recognize.py报错

### ISSUE THREAD

**Issue by aresgogo** [libai3/masr#35]
ares@ares-ubuntu18:~/bin/masr$ python examples/demo-recognize.py 
Traceback (most recent call last):
  File "examples/demo-recognize.py", line 3, in <module>
    from models.conv import GatedConv
  File "/home/ares/bin/masr/examples/../models/conv.py", line 1, in <module>
    import torch
  File "/home/ares/.local/lib/python2.7/site-packages/torch/__init__.py", line 263, in <module>
    from .functional import *
  File "/home/ares/.local/lib/python2.7/site-packages/torch/functional.py", line 10, in <module>
    from typing import Optional, Tuple, List, Union
ImportError: No module named typing

**Comment by libai3** [comment]
It seems that you're using python2.
Please use python3 instead.
