### ISSUE TITLE
分析自己的wav时出错。

### ISSUE THREAD

**Issue by neoedmund** [libai3/masr#54]
由于不太懂这些库，不知道怎么回事. 应该是对音频文件内容容错性的问题？
```
/data/oss/masr/examples/../feature.py:20: RuntimeWarning: Mean of empty slice.
  wav = (wav - wav.mean()) / wav.std()
/home/neoe/.local/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/neoe/.local/lib/python3.6/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/neoe/.local/lib/python3.6/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/neoe/.local/lib/python3.6/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "examples/demo-recognize.py", line 6, in <module>
    text = model.predict("xxxxxxxxxx.wav")
  File "/data/oss/masr/examples/../models/conv.py", line 61, in predict
    spec = feature.spectrogram(wav)
  File "/data/oss/masr/examples/../feature.py", line 26, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/neoe/.local/lib/python3.6/site-packages/librosa/core/spectrum.py", line 165, in stft
    y = np.pad(y, int(n_fft // 2), mode=pad_mode)
  File "/home/neoe/.local/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1290, in pad
    " in axis {} of `array`".format(axis))
ValueError: There aren't any elements to reflect in axis 0 of `array`
```

**Comment by neoedmund** [comment]
只是测试数据wav文件
[sample2.zip](https://github.com/libai3/masr/files/3357072/sample2.zip)

**Comment by libai3** [comment]
As I see in #55 , it seems that you have solved this issue.
I've heared the sound file. Is this or something similar you wanna test?
I don't think masr will work on this. Even I can't tell what it's speaking.

**Comment by neoedmund** [comment]
No, this sample is about the wav format, not it's voice content. 
It's a playable wav file, maybe cannot be recognized, but should not throw out error.

**Comment by libai3** [comment]
Your wav file is 44100Hz, masr needs 16000Hz.
If you're not familiar with the libraries, always follow the README.

**Comment by neoedmund** [comment]
Not every 44100Hz file will a `ValueError`
