### ISSUE TITLE
使用提供模型作为baseline，不会出现loss为inf

### ISSUE THREAD

**Issue by v-yunbin** [libai3/masr#57]
使用作者提供的baseline model 直接训练模型，损失不在出现inf：

```
[1/1000][18377/35392]	Loss = 8.876114845275879
[1/1000][18378/35392]	Loss = 7.887100696563721
[1/1000][18379/35392]	Loss = 8.926383018493652
[1/1000][18380/35392]	Loss = 5.814878463745117
[1/1000][18381/35392]	Loss = 8.963436126708984
[1/1000][18382/35392]	Loss = 6.298241138458252
[1/1000][18383/35392]	Loss = 9.845922470092773
[1/1000][18384/35392]	Loss = 7.071393966674805
[1/1000][18385/35392]	Loss = 6.255049705505371
```
不过这么跑，得到的模型不能用，猜测作者应该是在完成基于baseline 模型去训练的工作，期待中。。祝好
```
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    model = GatedConv.load("pretrained/model_0.pth")
  File "/home/zyb/masr/models/base.py", line 13, in load
    state_dict = package["state_dict"]
TypeError: 'GatedConv' object is not subscriptable
```
查看提供的模型：
gated-conv.pth: 8086 relocatable (Microsoft)
查看自己训练的模型：
model_0.pth: 8086 relocatable (Microsoft)

**Comment by BeHappyForMe** [comment]
损失为负数是由什么引起的，有没有什么数学说法

**Comment by wangjianhua1** [comment]
> baseline model

如何修改代码，才能使用作者的baseline?
