### ISSUE TITLE
加入语言模型以后,长时间没有返回结果

### ISSUE THREAD

**Issue by zhouhao-learning** [libai3/masr#59]
我按照你的说明下载好了语言模型,然后传入一个`wav`格式的文件,进行预测,但是好多分钟都没有预测结果返回,预测代码如下:
```
import beamdecode


res = beamdecode.predict("test.wav")
print("识别结果:", res)
```
然后就终端一直没有返回识别结果了:
![image](https://user-images.githubusercontent.com/24581773/60796062-5c2f8180-a19f-11e9-8f25-ebefae2acfe7.png)

请问这是怎么回事呢?

**Comment by libai3** [comment]
What's the content of your test.wav?

**Comment by zhouhao-learning** [comment]
@libai3 
我的`test.wav`是一个14秒的语音,我上传给你一下,你看看什么问题呢

[test.wav.zip](https://github.com/libai3/masr/files/3367574/test.wav.zip)

**Comment by zhouhao-learning** [comment]
@libai3 
即便我使用你提供的test.wav进行测试,一样的,很长时间都没有输出预测结果

**Comment by libai3** [comment]
Then it's not the wave file to blame.
Sorry but I never encountered this. 
It works fine on Core-i5 CPU and it seems that your computer is better.
The only thing I can do to help you is leave this issue open to see if someone can help.

**Comment by zhouhao-learning** [comment]
好吧

**Comment by tonytan1701** [comment]
@zhouhao-learning 
<img width="626" alt="屏幕快照 2019-09-29 上午4 01 13" src="https://user-images.githubusercontent.com/15950953/65821851-e43c9900-e26d-11e9-94cc-d9c0cc806b15.png">  @你的语音文件是可以使用的。仅仅使用了作者libai3的预模型和推荐的语言模型就得到了这样的结果，给作者一个大赞！

**Comment by ForgetThatNight** [comment]
> @libai3
> 我的`test.wav`是一个14秒的语音,我上传给你一下,你看看什么问题呢
> 
> [test.wav.zip](https://github.com/libai3/masr/files/3367574/test.wav.zip)



> @zhouhao-learning
> <img alt="屏幕快照 2019-09-29 上午4 01 13" width="626" src="https://user-images.githubusercontent.com/15950953/65821851-e43c9900-e26d-11e9-94cc-d9c0cc806b15.png"> @你的语音文件是可以使用的。仅仅使用了作者libai3的预模型和推荐的语言模型就得到了这样的结果，给作者一个大赞！

为什么你的14秒都能识别，我的达到5秒钟就报错了呀？
识别结果:
/home/ml/masr/examples/../feature.py:20: RuntimeWarning: invalid value encountered in true_divide
  wav = (wav - wav.mean()) / wav.std()
Traceback (most recent call last):
  File "examples/predict.py", line 21, in <module>
    print(beamdecode.predict(file))
  File "/home/ml/masr/examples/../beamdecode.py", line 39, in predict
    spec = feature.spectrogram(wav)
  File "/home/ml/masr/examples/../feature.py", line 26, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/home/ml/anaconda3/envs/MASR/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
