### ISSUE TITLE
能否自己训练语言模型？

### ISSUE THREAD

**Issue by Augustusmyc** [libai3/masr#67]
想问下能不能用自己的数据训练语言模型？有没有可以参考的代码呢？

**Comment by wbjnpu** [comment]
同样有这个疑问，你自己加进去了么

**Comment by Augustusmyc** [comment]
没加进去。。

**Comment by liudatutu** [comment]
同问

**Comment by wbjnpu** [comment]
可以，用kenlm训练语言模型，替换掉百度的那个那么大的语言模型就可以了
大土土君 <notifications@github.com> 于 2019年8月29日 下午4:47写道：


同问

―

**Comment by wbjnpu** [comment]
可以用kenlm训练然后使用，特定场景下准确率还是很高的
大土土君 <notifications@github.com> 于 2019年8月29日 下午4:47写道：


同问

―

**Comment by wbjnpu** [comment]
可以用kenlm
大土土君 <notifications@github.com> 于 2019年8月29日 下午4:47写道：


同问

―

**Comment by WilliamEt** [comment]
> 可以，用kenlm训练语言模型，替换掉百度的那个那么大的语言模型就可以了 大土土君 <notifications@github.com> 于 2019年8月29日 下午4:47
我用了自己训练的语言模型，然后服务端就挂了
 File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/demo-client.py", line 14, in <module>
    r = requests.post(server, files=files)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/et/01Dev/conda/anaconda3/envs/masr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
