### ISSUE TITLE
运行python examples/demo-recognize.py报错 RuntimeError: code is too big

### ISSUE THREAD

**Issue by genghuan2005** [libai3/masr#70]
Traceback (most recent call last):
  File "examples/demo-recognize.py", line 6, in <module>
    text = model.predict("test.wav")
  File "/home/import/gh/masr/examples/../models/conv.py", line 64, in predict
    out = self.cnn(spec)
  File "/home/import/anaconda3/envs/torch101/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/import/anaconda3/envs/torch101/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/import/anaconda3/envs/torch101/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/import/gh/masr/examples/../models/conv.py", line 18, in forward
    x = self.conv(x)
  File "/home/import/anaconda3/envs/torch101/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/import/anaconda3/envs/torch101/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 187, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big

请问有解决的吗，我的torch 版本是1.0.1，librosa是0.7.0, numpy是1.16.4

**Comment by RenJinan** [comment]
请问你的问题解决了吗？是如何解决的

**Comment by genghuan2005** [comment]
> 请问你的问题解决了吗？是如何解决的
没有解决，你也遇到相同的问题了吗

**Comment by genghuan2005** [comment]
> 请问你的问题解决了吗？是如何解决的

你好 请问问题解决了吗

**Comment by feifaxiaoming** [comment]
你们也应该用的cpu的跑的吧，没有用gpu的吧 ，我用gpu的同样版本，就没问题，但是用cpu的这个版本运行就报这个问题

**Comment by bigcash** [comment]
RuntimeError: code is too big
有人知道这个是什么原因嘛，回滚到torch==1.0.1，还是报错的。
我的cuda是10.2，pytorch1.0.1,之前是torch1.3.1时也是报这个错误的

**Comment by icegomic** [comment]
https://github.com/pytorch/pytorch/issues/24174    我找到了一个解答 目前还在尝试 如果有成功的 麻烦说一下
