### ISSUE TITLE
在ubuntu环境中的问题

### ISSUE THREAD

**Issue by ZZT4552** [libai3/masr#96]
在最后执行pip install . 语句的时候报错
ERROR: Command errored out with exit status 1:
     command: /home/f306/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-near3np_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-near3np_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-near3np_/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-near3np_/setup.py", line 43, in <module>
        import build
      File "/tmp/pip-req-build-near3np_/build.py", line 8, in <module>
        import wget
    ModuleNotFoundError: No module named 'wget'
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ZZT4552** [comment]
请问有哪位大佬知道应该怎么解决么

**Comment by feifaxiaoming** [comment]
你没有安装这个'wget'包，pip install一下
